# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newproject

  target 'newproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'newproject-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newproject-tvOS

  target 'newproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
